$ANSIBLE_VAULT;1.1;AES256
30326338346366663863386136653531313564373061313661663533316339643963383865356438
3465653966333863326234326430343737363639376336350a313431626537643139633735343661
35353434376236623739363535386665343431343330303736393130323761303931623662643336
6633626633653634310a383332363661633033616535626431343134613537366535663031356135
34383532643539626466393934303439386364323332306165343363313235626330636331623034
61383664653664363936396466623538356637613634393438613662633730313233373361396534
36643534336338323931353532353931343635356663373663333431346534613364343133343864
36333965363165343437393933656131353666353134653962653837613838656261653065353066
65613030646235396536313266656361376433326339663036386337356630306138
