# roles/docker/tasks/main.yml
---
- name: DOCKER | Instalar pacotes de pré-requisito
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: DOCKER | Criar diretório de keyrings do apt se não existir
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: DOCKER | Adicionar a chave GPG oficial do Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true # Garante que a chave seja sempre a mais recente

- name: DOCKER | Adicionar o repositório do Docker
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: DOCKER | Instalar Docker Engine e Docker Compose Plugin
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin # Este é o novo 'docker compose' v2
    state: present
    update_cache: yes

- name: DOCKER | Garantir que o serviço Docker esteja iniciado e habilitado
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: DOCKER | Adicionar usuário ao grupo 'docker' (se definido)
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  when: docker_user is defined and docker_user != ""